[package]
name = "different-id-types"
version = "0.1.0"
authors = ["David Pedersen <david.pdrsn@gmail.com>"]
edition = "2018"

[dependencies]
diesel = { version = "1.4.2", features = ["postgres"] }
juniper = "0.12"
juniper-from-schema = "0.3.0"
juniper-eager-loading = "0.2.0"
